import Head from 'next/head'
import About from '../components/about'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Titan Intech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About/>
    </div>
  )
}
